export const MOBITEL_OVERVIEW_REQUEST = 'MOBITEL_OVERVIEW_REQUEST';
export const MOBITEL_OVERVIEW_SUCCESS = 'MOBITEL_OVERVIEW_SUCCESS';
export const MOBITEL_OVERVIEW_FAIL = 'MOBITEL_OVERVIEW_FAIL';

// ------------------------------

export const HUAWEI_FILTERED_VENDOR_NAMES_REQUEST = 'FILTERED_VENDOR_NAMES_REQUEST';
export const HUAWEI_FILTERED_VENDOR_NAMES_SUCCESS = 'FILTERED_VENDOR_NAMES_SUCCESS';
export const HUAWEI_FILTERED_VENDOR_NAMES_FAIL = 'FILTERED_VENDOR_NAMES_FAIL';

//------------------------------

export const ZTE_FILTERED_VENDOR_NAMES_REQUEST = 'ZTE_FILTERED_VENDOR_NAMES_REQUEST';
export const ZTE_FILTERED_VENDOR_NAMES_SUCCESS = 'ZTE_FILTERED_VENDOR_NAMES_SUCCESS';
export const ZTE_FILTERED_VENDOR_NAMES_FAIL = 'ZTE_FILTERED_VENDOR_NAMES_FAIL';

//-----------------------------

export const MOBITEL_CHART_COLUMN_DATA_REQUEST = 'MOBITEL_CHART_COLUMN_DATA';
export const MOBITEL_CHART_COLUMN_DATA_SUCCESS = 'MOBITEL_CHART_COLUMN_DATA_SUCCESS';
export const MOBITEL_CHART_COLUMN_DATA_FAIL = 'MOBITEL_CHART_COLUMN_DATA_FAIL';

//-----------------------------

export const MOBITEL_CHART_AREA_DATA_REQUEST = 'MOBITEL_CHART_AREA_DATA_REQUEST';
export const MOBITEL_CHART_AREA_DATA_SUCCESS = 'MOBITEL_CHART_AREA_DATA_SUCCESS';
export const MOBITEL_CHART_AREA_DATA_FAIL = 'MOBITEL_CHART_AREA_DATA_FAIL';

//-----------------------------

export const MOBITEL_DATABASE_REQUEST = 'MOBITEL_DATABASE_REQUEST';
export const MOBITEL_DATABASE_SUCCESS = 'MOBITEL_DATABASE_SUCCESS';
export const MOBITEL_DATABASE_FAIL = 'MOBITEL_DATABASE_FAIL';

//----------------------------

export const MOBITEL_OVERVIEW_REQUEST
